version: '3.3'

services:
  database:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'xss_teste'
      # So you don't have to use root, but you can if you like
      MYSQL_ROOT_USER: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      # MYSQL_ROOT_PASSWORD: root_password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  # app:
  #   build: .
  #   container_name: xss_session_hijacking
  #   ports:
  #       - 8080:8080
  #       # - 9229:9229
  #   volumes:
  #       - .:/usr/app
  #   links:
  #       - database
  #   depends_on:
  #       - database
# Names our volume
volumes:
  my-db: